version: "3"

services:
  wazigate-lora:
    container_name: wazigate-lora
    image: waziup/wazigate-lora
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WAZIGATE_EDGE=wazigate-edge:880
      - WAZIGATE_MQTT=wazigate-edg
    depends_on:
      - wazigate-edge
      - chirpstack-network-server
      - chirpstack-application-server
      - chirpstack-gateway-bridge
    volumes:
      - ./conf:/etc/wazigate-lora

  chirpstack-network-server:
    container_name: chirpstack-network-server
    image: arribada/chirpstack-networkserver
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./conf/chirpstack-network-server:/etc/chirpstack-network-server
    labels:
      io.waziup.wazigate.dep: "wazigate-lora"

  chirpstack-application-server:
    container_name: chirpstack-application-server
    image: arribada/chirpstack-app-server
    depends_on:
      - postgresql
      - redis
    ports:
      - 8080:8080
    volumes:
      - ./conf/chirpstack-application-server:/etc/chirpstack-application-server
    labels:
      io.waziup.wazigate.dep: "wazigate-lora"

  chirpstack-gateway-bridge:
    container_name: chirpstack-gateway-bridge
    image: arribada/chirpstack-gateway-bridge
    ports:
      - 1700:1700/udp
    volumes:
      - ./conf/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    labels:
      io.waziup.wazigate.dep: "wazigate-lora"

  postgresql:
    container_name: postgresql
    image: postgres:9.6-alpine
    volumes:
      - ./conf/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    labels:
      io.waziup.wazigate.dep: "wazigate-lora"

  redis:
    container_name: redis
    image: redis:5-alpine
    volumes:
      - redisdata:/data
    labels:
      io.waziup.wazigate.dep: "wazigate-lora"

volumes:
  postgresqldata:
  redisdata:
